### ISSUE TITLE
mistake in model.py?

### ISSUE THREAD

**Issue by linbaiwpi** [timctho/mobilenet-v2#3]
in model.py
Line 169 "self.output = self._inverted_bottleneck(self.output, 6, 96, 0)"

is supposed to be "self.output = self._inverted_bottleneck(self.output, 6, 96, **1**)"
please check

**Comment by timctho** [comment]
I don't think there's a mistake. You're doing one more downsample which will results in wrong feature map size.

**Comment by linbaiwpi** [comment]
you are right, at that line, stride=1 instead of 2. sorry.
I'll close this issue
